# Generated by Django 5.0.6 on 2024-07-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_following',
        ),
    ]
