# Generated by Django 5.0.6 on 2024-07-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_liked_remove_profile_is_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.profile'),
        ),
    ]
