# Generated by Django 5.0.6 on 2024-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='net_followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='net_followings',
        ),
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
