# Generated by Django 5.0.6 on 2024-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_profile_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.JSONField(default=list, null=True),
        ),
    ]
