# Generated by Django 5.0.6 on 2024-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_profile_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.JSONField(default=list, null=True),
        ),
    ]
