# Generated by Django 5.0.6 on 2024-07-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
