# Generated by Django 5.0.6 on 2024-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_post_like_count_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
