# Generated by Django 5.0.6 on 2024-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='net_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='net_followings',
            field=models.IntegerField(default=0),
        ),
    ]
